# Generated by Django 5.1.12 on 2025-10-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stickers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_name', models.CharField(max_length=100, unique=True)),
                ('sticker_file_addr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('access_level', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.boards')),
                ('author_id', models.ForeignKey(on_delete=models.SET(2), to='api.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_creation', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.threads')),
                ('user_id', models.ForeignKey(on_delete=models.SET(2), to='api.users')),
            ],
        ),
    ]
