# Generated by Django 5.1.12 on 2025-10-08 17:00

from django.db import migrations
from django.conf import settings


def add_default_users(apps, schema_editor):
    # this thing is supposed to give me a reference to table I ant to interract with
    # also I HAVE to include schema_editor but my linter yells at me for not using argument bruh
    Users = apps.get_model('api', 'Users')
    Users.objects.create(
        id=settings.ANONYMOUS_USER_ID,
        username='Anonymous',
        access_level='user',
        email='noreply@gmail.com',
        # okay so I didn't know how to make an unusable user hash so I asked
        # LLM and it told me one-char hash won't pass the test, so I guess I gotta trust em
        # cause I'm scared to use another lib
        passwd='!',
    )
    Users.objects.create(
        id=settings.DELETED_USER_ID,
        username='Deleted',
        access_level='user',
        email='noreply@gmail.com',
        # okay so I didn't know how to make an unusable user hash so I asked
        # LLM and it told me one-char hash won't pass the test, so I guess I gotta trust em cause I'm scared to use another lib
        passwd='!',
    )


def delete_default_users(apps, schema_editor):
    Users = apps.get_model('api', 'Users')
    for user_id in settings.DEFAULT_USERS_ID_ARRAY:
        try:
            Users.objects.get(id=user_id).delete()
        except Users.DoesNotExist:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_users, delete_default_users),
    ]
