# Generated by Django 5.1.12 on 2025-10-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251008_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access_level',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
