# Generated by Django 5.1.12 on 2025-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_access_level_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='noreply@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
